import type { NextPage } from 'next'
import Head from 'next/head'
import { Masthead } from '@/components/Masthead'
import { AboutUs } from '@/components/AboutUs'
import { Skills } from '@/components/Skills'
import { Works } from '@/components/Works'
import { TrustedBy } from '@/components/TrustedBy'
import { ContactUs } from '@/components/ContactUs'
import { Footer } from '@/components/Footer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Margelo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Masthead />
        <AboutUs />
        <Skills />
        <Works />
        <TrustedBy />
        <ContactUs />
      </main>
      <Footer />
    </>
  )
}

export default Home
